# Generated by Django 5.1 on 2024-10-19 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EPIgenerico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('prazo_dias', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('condicoes', models.CharField(max_length=100)),
                ('status', models.IntegerField(db_default=0)),
                ('data_prevista', models.DateField(null=True)),
                ('data_devolução', models.DateField(null=True)),
                ('data_emprestimo', models.DateField(null=True)),
                ('id_EPIgenerico_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.epigenerico')),
            ],
        ),
    ]
